version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

test_patterns = \[  
  "tests/\*\*",  
  "test_\*.py"  
]