from pathlib import Path
from typing import Dict, List, Optional, Union

from QeHelper import QeHelper

class QeDataBase(QeHelper):
    @classmethod
    def load(cls, file_name: Optional[Union[str, None]]) -> Union[List[Path], Path]: ...
    @classmethod
    def write(cls, data: Dict, file_name: str) -> None: ...
    @classmethod
    def read(cls, file_name: Optional[Union[str, None]]) -> Dict: ...
    @classmethod
    def create(cls, file_name: str) -> None: ...
    @classmethod
    def delete(cls, file_name: str) -> None: ...
