from typing import Dict, List

class QeDataBase:
    @classmethod
    def write(cls, data: Dict[str, List[List[int]]], file_path: str) -> None: ...
    @classmethod
    def read(cls, file_path: str) -> Dict[str, List[List[int]]]: ...
    @classmethod
    def create(cls, file_path: str) -> None: ...
    @classmethod
    def delete(cls, file_path: str) -> None: ...
