from typing import Dict, List

from QeLib.QeHelper import QeHelper

class QeDataBase(QeHelper):
    @classmethod
    def get_json_file_path(cls, file_name: str) -> str: ...
    @classmethod
    def write(cls, data: Dict[str, List[List[int]]], file_name: str) -> None: ...
    @classmethod
    def read(cls, file_name: str) -> Dict[str, List[List[int]]]: ...
    @classmethod
    def create(cls, file_name: str) -> None: ...
    @classmethod
    def delete(cls, file_name: str) -> None: ...
