name: Sten's Python CI/CD
run-name: "Sten's Python CI/CD"

on:
  push:
    branches:
      - main

jobs:
  keyword_check:
    name: Keyword Check
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, '.deploy')
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - id: keyword_check
        run: echo "Keyword Check Passed"

  code_quality:
    name: Code Quality Check
    needs: [keyword_check, testing]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: pip install pycodestyle

      - name: Run PyCodeStyle
        run: pycodestyle .

      - id: code_quality_badge
        if: always()
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: code_quality_badge.json
          label: Code Quality
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          namedLogo: codacy
          logoColor: white
          style: flat-square

  testing:
    name: Pytests
    needs: [keyword_check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: |
          pip install pytest
          pip install pytest-md
          pip install pytest-emoji

      - id: test_run_and_report
        uses: pavelzw/pytest-action@main
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: "-q"
          click-to-expand: true
          report-title: "Test Report"

      - id: pytest_badge
        if: always()
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: pytest_badge.json
          label: pytest
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          namedLogo: pytest
          logoColor: white
          style: flat-square

  release:
    name: Release
    needs: [testing]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: |
          pip install build
          pip install setuptools

      - id: build_package
        name: Build Package
        run: python -m build

      - id: create_tag
        name: Create & Push Tag
        run: echo TAG=$(python setup.py --version) >> $GITHUB_OUTPUT
        shell: bash

      - id: create_release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - id: release_badge
        if: always()
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: release_badge.json
          label: Release
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          namedLogo: hackthebox
          logoColor: white
          style: flat-square

  publish:
    name: Publish
    needs: [testing]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install build
          pip install twine

      - id: build_package
        name: Build Package
        run: python -m build

      - id: publish_to_pypi
        name: Publish Package to PyPI
        if: contains(github.event.head_commit.message, '.deploy')
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - id: publish_to_testpypi
        name: Publish Package to TestPyPI
        if: contains(github.event.head_commit.message, '.deploy .test')
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}

      - id: pypi_badge
        if: always()
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: pypi_badge.json
          label: PyPI
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          namedLogo: pypi
          logoColor: white
          style: flat-square

  documentation:
    name: Documentation
    needs: [testing]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: |
          pip install sphinx
          pip install sphinx_rtd_theme

      - id: build_docs
        name: Build Sphinx Documentation
        run: make html
        working-directory: StenLib/docs

      - id: copy_docs
        uses: mdallasanta/ssh-scp-deploy@main
        with:
          local: "./StenLib/docs/_build/html/*"
          remote: "${{ secrets.SSH_HOST_PATH }}"
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_HOST_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_options: -oHostKeyAlgorithms=+ssh-dss

      - id: docs_badge
        if: always()
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: docs_badge.json
          label: Docs
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          namedLogo: googledocs
          logoColor: white
          style: flat-square
