name: Sten's Setup Python CI/CD
run-name: "Sten's Setup Python CI/CD"

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@main

      - id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: "pip"
