name: Python Package Deployment TEST

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for keyword in commit message
        id: keyword_check
        run: echo "contains_keyword=$(echo '${{ github.event.head_commit.message }}' | grep -q '.test' && echo true || echo false)" >> $GITHUB_ENV

      - name: Conditional Step
        if: steps.keyword_check.outputs.contains_keyword == 'true'
        run: echo "Keyword found in commit message. Running deployment steps..."

      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install twine
          pip install mypy

      - name: Generate .pyi stub files
        run: |
          mypy --stub-output ./

      - name: Create & Push tag
        id: create_tag
        run: |
          TAG=$(echo '${{ github.event.head_commit.message }}' | grep -oP '.tag\[\K(.*?)(?=\])')
          if [ -n "$TAG" ]; then
            git tag $TAG
            git push origin $TAG
          else
            TAG="NULL"
            git tag $TAG
            git push origin $TAG
            echo "No tag found in commit message. Using default tag."
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.create_tag.outputs.TAG }}
        with:
          tag_name: ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Publish package to TestPyPI
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
